Fixed?
tried some things and just changed Tourlogs class name to TourlogsComponent to try and fix the tourlogs, cause they dont show up beneath thier tour, didnt work out, then for some reasen got errors:Component update failed: ctx.selectedTourId is not a function
TourlogsComponent_Template@http://localhost:4200/@ng/component?c=src%2Fapp%2Ftourlogs%2Ftourlogs.ts%40TourlogsComponent&t=1775575039096:235:53
executeTemplate@http://localhost:4200/@fs/C:/Users/Simon/Bachelor%20Informatik%20FH%20Technikum%20Wien/2026SS/SWEN2/SWEN2-route-planner/SWEN_2_RoutePlanner/.angular/cache/21.2.5/SWEN_2_RoutePlanner/vite/deps/chunk-4VWXJOD2.js?v=2b0b80c4:11344:15
refreshView@http://localhost:4200/@fs/C:/Users/Simon/Bachelor%20Informatik%20FH%20Technikum%20Wien/2026SS/SWEN2/SWEN2-route-planner/SWEN_2_RoutePlanner/.angular/cache/21.2.5/SWEN_2_RoutePlanner/vite/deps/chunk-4VWXJOD2.js?v=2b0b80c4:12004:22
recreate@http://localhost:4200/@fs/C:/Users/Simon/Bachelor%20Informatik%20FH%20Technikum%20Wien/2026SS/SWEN2/SWEN2-route-planner/SWEN_2_RoutePlanner/.angular/cache/21.2.5/SWEN_2_RoutePlanner/vite/deps/chunk-4VWXJOD2.js?v=2b0b80c4:23138:16
executeWithInvalidateFallback@http://localhost:4200/@fs/C:/Users/Simon/Bachelor%20Informatik%20FH%20Technikum%20Wien/2026SS/SWEN2/SWEN2-route-planner/SWEN_2_RoutePlanner/.angular/cache/21.2.5/SWEN_2_RoutePlanner/vite/deps/chunk-4VWXJOD2.js?v=2b0b80c4:23148:5
recreateLView/<@http://localhost:4200/@fs/C:/Users/Simon/Bachelor%20Informatik%20FH%20Technikum%20Wien/2026SS/SWEN2/SWEN2-route-planner/SWEN_2_RoutePlanner/.angular/cache/21.2.5/SWEN_2_RoutePlanner/vite/deps/chunk-4VWXJOD2.js?v=2b0b80c4:23143:49
run@http://localhost:4200/@fs/C:/Users/Simon/Bachelor%20Informatik%20FH%20Technikum%20Wien/2026SS/SWEN2/SWEN2-route-planner/SWEN_2_RoutePlanner/.angular/cache/21.2.5/SWEN_2_RoutePlanner/vite/deps/chunk-4VWXJOD2.js?v=2b0b80c4:6001:15
recreateLView@http://localhost:4200/@fs/C:/Users/Simon/Bachelor%20Informatik%20FH%20Technikum%20Wien/2026SS/SWEN2/SWEN2-route-planner/SWEN_2_RoutePlanner/.angular/cache/21.2.5/SWEN_2_RoutePlanner/vite/deps/chunk-4VWXJOD2.js?v=2b0b80c4:23143:10
recreateMatchingLViews@http://localhost:4200/@fs/C:/Users/Simon/Bachelor%20Informatik%20FH%20Technikum%20Wien/2026SS/SWEN2/SWEN2-route-planner/SWEN_2_RoutePlanner/.angular/cache/21.2.5/SWEN_2_RoutePlanner/vite/deps/chunk-4VWXJOD2.js?v=2b0b80c4:23092:18
recreateMatchingLViews@http://localhost:4200/@fs/C:/Users/Simon/Bachelor%20Informatik%20FH%20Technikum%20Wien/2026SS/SWEN2/SWEN2-route-planner/SWEN_2_RoutePlanner/.angular/cache/21.2.5/SWEN_2_RoutePlanner/vite/deps/chunk-4VWXJOD2.js?v=2b0b80c4:23105:29
recreateMatchingLViews@http://localhost:4200/@fs/C:/Users/Simon/Bachelor%20Informatik%20FH%20Technikum%20Wien/2026SS/SWEN2/SWEN2-route-planner/SWEN_2_RoutePlanner/.angular/cache/21.2.5/SWEN_2_RoutePlanner/vite/deps/chunk-4VWXJOD2.js?v=2b0b80c4:23102:31
recreateMatchingLViews@http://localhost:4200/@fs/C:/Users/Simon/Bachelor%20Informatik%20FH%20Technikum%20Wien/2026SS/SWEN2/SWEN2-route-planner/SWEN_2_RoutePlanner/.angular/cache/21.2.5/SWEN_2_RoutePlanner/vite/deps/chunk-4VWXJOD2.js?v=2b0b80c4:23105:29
ɵɵreplaceMetadata@http://localhost:4200/@fs/C:/Users/Simon/Bachelor%20Informatik%20FH%20Technikum%20Wien/2026SS/SWEN2/SWEN2-route-planner/SWEN_2_RoutePlanner/.angular/cache/21.2.5/SWEN_2_RoutePlanner/vite/deps/chunk-4VWXJOD2.js?v=2b0b80c4:23068:31
TourlogsComponent_HmrLoad/<@http://localhost:4200/main.js:2073:36

Please consider reporting the error at https://github.com/angular/angular-cli/issues

Then suddenly the tourlogs sind einfach wieder unter den tours gewesen, No idea why it suddenly works